title: "CookingMap"
url: "https://mikamichiels.github.io"
baseurl: "/CookingMap"

# Load the Thalloo theme remotely
remote_theme: AndrewIOM/thalloo-starter
plugins:
  - jekyll-remote-theme

# Make the maps collection build actual pages
collections:
  maps:
    output: true
    permalink: /maps/:name/

