title: "SLR studies per country"
url: "https://mikamichiels.github.io"
baseurl: "/CookingMap"
data: "/map-data/studies.csv"
lat: "lat"
lon: "lon"
size: "n_studies"
popup: "title"
colorby: "region"     # optional; shows different colors by UN region
cluster: true         # optional; cluster markers if many overlap
