title: "Clean Cooking SLR Map"
description: "Systematic review of clean cooking adoption studies — interactive evidence map."

baseurl: "/thalloo-starter" # the subpath of your site, e.g. /blog
url: "http://acm.im" # the base hostname & protocol for your site
ownername: "Your Website Name"
ownerurl: "https://your.website.url"

# Internal configuration
plugins:
  - jekyll-remote-theme
remote_theme: AndrewIOM/thalloo
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
